config/routes.rb
Rails.application.routes.draw do
  # Userログイン状態でのパス
  authenticated :user do
    root "user/top#index", as: "user_authenticated_root"
  end

  # User非ログイン状態でのルートパス
  root 'top#index'

  devise_for :users, module: 'user/devise', controllers: {
    registrations: 'user/devise/registrations',
    omniauth_callbacks: "user/devise/omniauth_callbacks"
  }

  resources :workspaces, only: [:index, :show, :new, :create, :destroy] do
    resource :workspace_users, only: [:create, :destroy]
    resource :boards, only: [:new, :create]

    scope module: :workspace do
      collection do
        resources :join_requests, only: [:index, :destroy], as: :workspace_join_request
      end
      resources :join_requests, only: [:new, :create]
    end
  end

  resources :boards, only: [:index, :show, :edit, :update, :destroy] do
    resources :task_lists, only: [:new, :create]
    resource :board_users, only: [:create, :destroy]
  end

  resources :task_lists, only: [:destroy] do
    resources :tasks, only: [:new, :create]
  end

  resources :tasks, only: [:show, :edit, :update, :destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list
  has_one :board, through: :task_list

  validates :title, presence: true  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmation_board, only: [:new, :create]

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task.board
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(update_params)
      redirect_to task_url(@task)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to board_url(@task.board_id)
    else
      render :edit
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :memo).merge(task_list_id: params[:task_list_id])
  end

  def update_params
    params.require(:task).permit(:title, :memo)
  end

  def confirmation_board
    task_list = TaskList.find(params[:task_list_id])
    unless current_user.boards.include?(task_list.board)
      if current_user.workspaces.include?(task_list.board.workspace)
        redirect_to task_list.board.workspace, alert: "ボードに参加していないため変更を行えません。" and return
      else
        redirect_to root_url, alert: "そのリストは存在しません。"
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<div class="container mx-auto">
  <div class="mt-8">
    <div class="relative">
      <h2 class="text-center text-2xl font-bold">タスク編集</h2>
      <%= link_to "削除", task_path(@task), method: :delete, class: "block absolute right-0 px-3 py-1 rounded bg-red-600 text-white", data: { confirm: "本当に削除しますか？" } %>
    </div>
    <%= form_with model: @task, url: task_path(@task) do |f|  %>
      <%= f.label :title, class: "block mt-6 font-bold" %>
      <%= f.text_field :title, class: "block w-full mt-2 rounded-lg shadow border-gray-400", autofocus: true %>

      <%= f.label :memo, class: "block mt-6 font-bold" %>
      <%= f.text_area :memo, class: "block h-40 w-full mt-2 p-4 rounded-lg shadow border-gray-400" %>

      <%= f.submit "変更", class: "block w-full mt-2 py-2 rounded shadow border bg-green-600 text-white" %>
    <% end %>
    <%= link_to "キャンセル", task_path(@task), class: "block py-2 px-auto text-center underline" %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container mx-auto items-center">
  <h2 class= "my-8 text-center text-3xl font-bold">タスク追加</h2>
  <%= form_with model: @task, url: task_list_tasks_path(params[:task_list_id]), class: "space-y-4" do |f| %>
    <div>
      <%= f.label :title, class: "block font-bold" %>
      <%= f.text_field :title, class: "block w-full mt-1 rounded-lg border-gray-400", autofocus: true %>
      <p class="field_with_errors text-right"><%= @task.errors.full_messages_for(:title).first %></p>
    </div>

    <div>
      <%= f.label :memo, class: "block font-bold" %>
      <%= f.text_area :memo, class: "block w-full mt-1 p-2 rounded-lg border-gray-400" %>
      <p class="field_with_errors text-right"><%= @task.errors.full_messages_for(:memo).first %></p>
    </div>

    <%= f.submit "追加", class: "w-full mt-6 py-2 rounded-md bg-blue-500 border text-white" %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container mx-auto">
  <div class="mt-6 px-6 py-8 rounded-xl bg-gray-100 border border-gray-400 shadow-lg">
    <div>
      <h2 class="text-3xl font-bold"><i class="fa-solid fa-bars-progress mr-4"></i><%= @task.title %></h2>
    </div>

    <div class="mt-4">
      <h3 class="text-xl font-bold"><i class="fa-solid fa-align-left"></i><span class="ml-4 text-base">説明</span></h3>
      <div class="min-h-[6rem] mt-2 p-2 bg-white border border-gray-400 shadow-inner rounded-lg">
        <div class="prose">
          <%= markdown(@task.memo).html_safe %>
        </div>
      </div>
      <p class="mt-2 text-right underline"><%= link_to "タスク編集", edit_task_path %></p>
    </div>
  </div>
</div>