config/routes.rb
Rails.application.routes.draw do
  # Userログイン状態でのパス
  authenticated :user do
    root "user/top#index", as: "user_authenticated_root"
  end

  # User非ログイン状態でのルートパス
  root 'top#index'

  devise_for :users, module: 'user/devise', controllers: {
    registrations: 'user/devise/registrations',
    omniauth_callbacks: "user/devise/omniauth_callbacks"
  }

  resources :workspaces, only: [:index, :show, :new, :create, :destroy] do
    resource :workspace_users, only: [:create, :destroy]
    resource :boards, only: [:new, :create]

    scope module: :workspace do
      collection do
        resources :join_requests, only: [:index, :destroy], as: :workspace_join_request
      end
      resources :join_requests, only: [:new, :create]
    end
  end

  resources :boards, only: [:index, :show, :edit, :update, :destroy] do
    resources :task_lists, only: [:new, :create]
    resource :board_users, only: [:create, :destroy]
  end

  resources :task_lists, only: [:destroy] do
    resources :tasks, only: [:new, :create]
  end

  resources :tasks, only: [:show, :edit, :update, :destroy]
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :workspace_users, dependent: :destroy
  has_many :users, through: :workspace_users
  has_many :join_requests, class_name: "WorkspaceJoinRequest", dependent: :destroy
  has_many :join_request_senders, through: :join_requests, source: :sender
  has_many :join_request_recipients, through: :join_requests, source: :recipient
  has_many :boards, dependent: :destroy
  
  validates :name, presence: true
  validates :color, presence: true
end

app/controllers/workspace/join_requests_controller.rb
class Workspace::JoinRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmation_workspace, only: [:new, :create]
  before_action :confirmation_request, only: [:destroy]

  def index
    @requests = current_user.workspace_join_requests.includes(:workspace, :sender, :recipient)
  end

  def new
    workspace = Workspace.includes(:join_requests, :join_request_recipients).find(params[:workspace_id])
    @join_requests = workspace.join_requests

    if params[:search].present?
      @users = User.search_unique_id(params[:search].split)
    else
      @users = User.none
    end
  end

  def create
    user = User.find(params[:user])
    workspace = Workspace.includes(:join_request_recipients, :users).find(params[:workspace_id])
    if workspace.users.include?(user)
      redirect_to new_workspace_join_request_url(workspace), alert: "そのユーザーはすでに所属しています。"
    elsif workspace.join_request_recipients.include?(user)
      redirect_to new_workspace_join_request_url(workspace), alert: "そのユーザーはすでに招待済みです。"
    else
      join_request = WorkspaceJoinRequest.new(sender: current_user, recipient: user, workspace: workspace)
      if join_request.save
        redirect_to new_workspace_join_request_url(workspace), notice: "#{user.unique_id} を招待しました。"
      else
        redirect_to new_workspace_join_request_url(workspace), alert: "招待に失敗しました。"
      end
    end
  end

  def destroy
    join_request = WorkspaceJoinRequest.includes(:workspace).find(params[:id])

    if join_request.destroy
      redirect_back fallback_location: root_url, alert: "ワークスペースへの招待を取り消しました。" and return
    else
      if join_request.recipient == current_user
        redirect_to workspace_join_request_index_url
      else
        redirect_to join_request.workspace
      end
    end
  end

  private
  def confirmation_workspace
    if params[:workspace_id].present?
      workspace = Workspace.includes(:users).find(params[:workspace_id])
      if workspace.users.exclude?(current_user)
        redirect_to root_url, alert: "ワークスペースが存在しません。"
      end
    else
      redirect_to root_url, alert: "エラーが発生しました。"
    end
  end

  def confirmation_request
    if params[:id].present?
      request = WorkspaceJoinRequest.find(params[:id])
      unless request.workspace.users.include?(current_user) or request.recipient == current_user
        redirect_to root_url, alert: "ワークスペースが存在しません。"
      end
    else
      redirect_to root_url, alert: "エラーが発生しました。"
    end
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmation_workspace, only: [:show, :destroy]

  def index
    @workspaces = current_user.workspaces
  end

  def show
    @workspace = Workspace.includes(:boards, :users).find(params[:id])
    @boards = @workspace.boards
    @users = @workspace.users
  end

  def new
    @workspace = Workspace.new
  end

  def create
    @workspace = Workspace.new(workspace_params)
    if @workspace.save
      current_user.workspaces << @workspace
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    workspace = Workspace.find(params[:id])
    
    if workspace.destroy
      redirect_to root_url and return
    else
      render :show
    end
  end

  private
  def workspace_params
    params.require(:workspace).permit(:name, :color)
  end

  def confirmation_workspace
    workspace = Workspace.find(params[:id])
    unless current_user.workspaces.include?(workspace)
      redirect_to root_url, alert: "そのワークスペースは存在しません。"
    end
  end
end

app/helpers/workspace/join_requests_helper.rb
module Workspace::JoinRequestsHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/workspace/join_requests/index.html.erb
<div class="container mx-auto">
  <div class="my-8">
    <h2 class="text-3xl text-center font-bold">ワークスペース 招待一覧</h2>
  </div>

  <div>
    <h3 class="text-lg font-bold">ワークスペース招待</h3>
    <% if @requests.exists? %>
      <table class="table-auto w-full mt-2 shadow-lg text-center">
        <thead class="border border-gray-600">
          <tr class="shadow-md">
            <th class="py-2 border-r border-gray-600">ワークスペース名</th>
            <th class="py-2 border-r border-gray-600">招待者id</th>
            <th class="py-2 border-r border-gray-600"></th>
            <th class="py-2"></th>
          </tr>
        </thead>
        <tbody class="border border-gray-600">
          <% @requests.each do |request| %>
            <tr class="shadow">
              <td class="py-2 border-r border-gray-600"><%= request.workspace.name %></td>
              <td class="py-2 border-r border-gray-600"><%= request.sender.unique_id %></td>
              <td class="py-2 border-r border-gray-600"><%= link_to "参加", workspace_workspace_users_path(request.workspace, user: request.recipient), method: :post, class: "underline text-blue-500" %></td>
              <td class="py-2"><%= link_to "拒否", workspace_join_request_path(request), method: :delete, class: "underline text-red-500", data: {confirm: "ワークスペースへの招待を削除しますか？"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/workspace/join_requests/new.html.erb
<div class="container mx-auto px-4">
  <h2 class="my-8 text-center text-3xl font-bold">ワークスペースにユーザー招待</h2>
  <%= form_with url: request.original_url, method: :get do |f| %>
    <%= f.label(:search, class: "flex flex-wrap justify-between") do %>
      <h3 class="font-bold">ユーザーIDで検索</h3>
      <em class="text-gray-500">※複数検索を行う場合は半角空白で区切ってください</em>
    <% end %>
    <div class ="flex items-center space-x-4">
      <%= f.search_field :search, class: "w-full mt-1 rounded-full border-gray-400 shadow" %>
      <%= f.button class: "flex" do %>
        <i class="fa-solid fa-magnifying-glass h-6 w-6 text-blue-600 hover:scale-125"></i>
      <% end %>
    </div>
  <% end %>

  <% if @users.present? %>
    <div class="mt-6 rounded-t-lg shadow-md shadow-gray-400">
      <div class="flex justify-between px-4 py-3 rounded-t-lg shadow border border-b-2 border-gray-400 bg-gray-200">
        <h4 class="font-bold">ユーザーID</h4>
        <em class="text-gray-600"><%= @users.length %>人</em>
      </div>
      <ul>
        <% @users.each do |user| %>
          <li class="py-3 border border-gray-400 border-t-0">
            <i class="fa-solid fa-user ml-4"></i>
            <%= link_to user.unique_id, workspace_join_requests_path(params[:workspace_id], user: user), method: :post, class: "ml-2 hover:underline" %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-6">
    <h3 class="font-bold">招待済みユーザー</h3>
    <% if @join_requests.present? %>
      <div class="mt-1 rounded-t-lg shadow-md shadow-gray-400">
        <div class="px-4 py-3 rounded-t-lg shadow border border-b-2 border-gray-400 bg-gray-200">
          <h4 class="font-bold"><%= @join_requests.count %>人</h4>
        </div>
        <ul>
          <% @join_requests.each do |request| %>
            <li class="py-3 border border-gray-400 border-t-0">
              <i class="fa-solid fa-user ml-4"></i>
              <span class="ml-2"><%= request.recipient.unique_id %></span>
              <%= link_to "招待取り消し", workspace_join_request_path(request), method: :delete, class: "underline", data: {confirm: "#{request.recipient.unique_id} への、ワークスペース招待を取り消しますか？"} %>
            </li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <p class="mt-2 text-gray-500">なし</p>
    <% end %>
  </div>
</div>