config/routes.rb
Rails.application.routes.draw do
  # Userログイン状態でのパス
  authenticated :user do
    root "user/top#index", as: "user_authenticated_root"
  end

  # User非ログイン状態でのルートパス
  root 'top#index'

  devise_for :users, module: 'user/devise', controllers: {
    registrations: 'user/devise/registrations',
    omniauth_callbacks: "user/devise/omniauth_callbacks"
  }

  resources :workspaces, only: [:index, :show, :new, :create, :destroy] do
    resource :workspace_users, only: [:create, :destroy]
    resource :boards, only: [:new, :create]

    scope module: :workspace do
      collection do
        resources :join_requests, only: [:index, :destroy], as: :workspace_join_request
      end
      resources :join_requests, only: [:new, :create]
    end
  end

  resources :boards, only: [:index, :show, :edit, :update, :destroy] do
    resources :task_lists, only: [:new, :create]
    resource :board_users, only: [:create, :destroy]
  end

  resources :task_lists, only: [:destroy] do
    resources :tasks, only: [:new, :create]
  end

  resources :tasks, only: [:show, :edit, :update, :destroy]
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :workspace_users, dependent: :destroy
  has_many :users, through: :workspace_users
  has_many :join_requests, class_name: "WorkspaceJoinRequest", dependent: :destroy
  has_many :join_request_senders, through: :join_requests, source: :sender
  has_many :join_request_recipients, through: :join_requests, source: :recipient
  has_many :boards, dependent: :destroy
  
  validates :name, presence: true
  validates :color, presence: true
end

app/controllers/workspace/join_requests_controller.rb
class Workspace::JoinRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmation_workspace, only: [:new, :create]
  before_action :confirmation_request, only: [:destroy]

  def index
    @requests = current_user.workspace_join_requests.includes(:workspace, :sender, :recipient)
  end

  def new
    workspace = Workspace.includes(:join_requests, :join_request_recipients).find(params[:workspace_id])
    @join_requests = workspace.join_requests

    if params[:search].present?
      @users = User.search_unique_id(params[:search].split)
    else
      @users = User.none
    end
  end

  def create
    user = User.find(params[:user])
    workspace = Workspace.includes(:join_request_recipients, :users).find(params[:workspace_id])
    if workspace.users.include?(user)
      redirect_to new_workspace_join_request_url(workspace), alert: "そのユーザーはすでに所属しています。"
    elsif workspace.join_request_recipients.include?(user)
      redirect_to new_workspace_join_request_url(workspace), alert: "そのユーザーはすでに招待済みです。"
    else
      join_request = WorkspaceJoinRequest.new(sender: current_user, recipient: user, workspace: workspace)
      if join_request.save
        redirect_to new_workspace_join_request_url(workspace), notice: "#{user.unique_id} を招待しました。"
      else
        redirect_to new_workspace_join_request_url(workspace), alert: "招待に失敗しました。"
      end
    end
  end

  def destroy
    join_request = WorkspaceJoinRequest.includes(:workspace).find(params[:id])

    if join_request.destroy
      redirect_back fallback_location: root_url, alert: "ワークスペースへの招待を取り消しました。" and return
    else
      if join_request.recipient == current_user
        redirect_to workspace_join_request_index_url
      else
        redirect_to join_request.workspace
      end
    end
  end

  private
  def confirmation_workspace
    if params[:workspace_id].present?
      workspace = Workspace.includes(:users).find(params[:workspace_id])
      if workspace.users.exclude?(current_user)
        redirect_to root_url, alert: "ワークスペースが存在しません。"
      end
    else
      redirect_to root_url, alert: "エラーが発生しました。"
    end
  end

  def confirmation_request
    if params[:id].present?
      request = WorkspaceJoinRequest.find(params[:id])
      unless request.workspace.users.include?(current_user) or request.recipient == current_user
        redirect_to root_url, alert: "ワークスペースが存在しません。"
      end
    else
      redirect_to root_url, alert: "エラーが発生しました。"
    end
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmation_workspace, only: [:show, :destroy]

  def index
    @workspaces = current_user.workspaces
  end

  def show
    @workspace = Workspace.includes(:boards, :users).find(params[:id])
    @boards = @workspace.boards
    @users = @workspace.users
  end

  def new
    @workspace = Workspace.new
  end

  def create
    @workspace = Workspace.new(workspace_params)
    if @workspace.save
      current_user.workspaces << @workspace
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    workspace = Workspace.find(params[:id])
    
    if workspace.destroy
      redirect_to root_url and return
    else
      render :show
    end
  end

  private
  def workspace_params
    params.require(:workspace).permit(:name, :color)
  end

  def confirmation_workspace
    workspace = Workspace.find(params[:id])
    unless current_user.workspaces.include?(workspace)
      redirect_to root_url, alert: "そのワークスペースは存在しません。"
    end
  end
end

app/helpers/workspace/join_requests_helper.rb
module Workspace::JoinRequestsHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/workspaces/index.html.erb
<div class="container mx-auto">
  <div class="my-8">
    <h2 class="text-3xl text-center font-bold">所属ワークスペース一覧</h2>
  </div>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
    <% @workspaces.each do |workspace| %>
      <div class="col-span-1 panel-3d h-24 rounded-md border border-gray-600" style="background-color: <%= workspace.color %>;">
        <%= link_to workspace, class: "group block h-full p-2" do %>
          <p class="text-white text-lg font-bold group-hover:underline"><%= workspace.name %></p>
        <% end %>
      </div>
    <% end %>
  </div>
  <p class="mt-4 text-right"><%= link_to "ワークスペースを作成", new_workspace_path, class: "line-link" %></p>
</div>

app/views/workspaces/new.html.erb
<div class="container mx-auto">
  <h2 class="my-8 text-center text-3xl font-bold">ワークスペース作成</h2>
  <%= form_with model: @workspace, class: "space-y-3" do |f| %>
    <div>
      <%= f.label :name, class: "block font-bold" %>
      <%= f.text_field :name, class: "block w-full mt-1 rounded-lg border-gray-400", autofocus: true %>
      <p class="field_with_errors text-right"><%= @workspace.errors.full_messages_for(:name).first %></p>
    </div>

    <div>
      <%= f.label :color, class: "block font-bold" %>
      <%= f.color_field :color %>
      <p class="field_with_errors text-right"><%= @workspace.errors.full_messages_for(:color).first %></p>
    </div>

    <div>
      <%= f.submit "作成", class: "w-full py-2 rounded-md bg-blue-500 border text-white btn-3d" %>
    </div>
  <% end %>
</div>

app/views/workspaces/show.html.erb
<div class="container mx-auto">
  <h2 class="my-8 text-center text-3xl font-bold"><%= @workspace.name %></h2>

  <div>
    <h3 class="font-bold text-lg">ボード</h3>
    <div class="mt-1 p-2 rounded bg-gray-300 shadow shadow-gray-500">
      <ul class="flex overflow-x-auto space-x-4">
        <% @boards.each do |board| %>
          <li class="panel-3d h-24 mx-1 my-2 rounded-md border border-gray-600" style="background-color: <%= board.color %>;">
            <%= link_to board, class: "group block h-full min-w-[15rem] p-2" do %>
              <p class="font-bold text-white text-lg group-hover:underline"><%= board.name %></p>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <p class="h-6 mt-2 text-right"><%= link_to "ボード追加", new_workspace_boards_path(@workspace), class: "line-link" %></p>
  </div>

  <div class="mt-4">
    <div class="flex justify-between">
      <h3 class="font-bold text-lg">
        <i class="fa-solid fa-user-group"></i>
        メンバー
      </h3>
      <p class="h-6"><i class="fa-solid fa-user-plus"></i><%= link_to "ユーザー招待", new_workspace_join_request_path(@workspace), class: "line-link" %></p>
    </div>

    <ul class="mx-6">
      <% @users.each do |user| %>
        <li class="mt-1"><%= user.unique_id %></li>
      <% end %>
    </ul>

    <% if @users.include?(current_user) %>
      <div class="mt-4">
        <p class="h-6"><%= link_to "ワークスペースから退出", workspace_workspace_users_path(@workspace, user: current_user.id), method: :delete, class: "line-link", data: {confirm: "本当にワークスペースから退出してよろしいですか？"} %></p>
      </div>
    <% end %>
  </div>
  <p class="h-6"><%= link_to "ワークスペース削除", @workspace, method: :delete, class: "line-link", data: {confirm: "本当にワークスペースを削除しますか？"} %></p>
</div>