config/routes.rb
Rails.application.routes.draw do
  # Userログイン状態でのパス
  authenticated :user do
    root "user/top#index", as: "user_authenticated_root"
  end

  # User非ログイン状態でのルートパス
  root 'top#index'

  devise_for :users, module: 'user/devise', controllers: {
    registrations: 'user/devise/registrations',
    omniauth_callbacks: "user/devise/omniauth_callbacks"
  }

  resources :workspaces, only: [:index, :show, :new, :create, :destroy] do
    resource :workspace_users, only: [:create, :destroy]
    resource :boards, only: [:new, :create]

    scope module: :workspace do
      collection do
        resources :join_requests, only: [:index, :destroy], as: :workspace_join_request
      end
      resources :join_requests, only: [:new, :create]
    end
  end

  resources :boards, only: [:index, :show, :edit, :update, :destroy] do
    resources :task_lists, only: [:new, :create]
    resource :board_users, only: [:create, :destroy]
  end

  resources :task_lists, only: [:destroy] do
    resources :tasks, only: [:new, :create]
  end

  resources :tasks, only: [:show, :edit, :update, :destroy]
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :workspace
  has_many :task_lists, dependent: :destroy
  has_many :tasks, through: :task_lists
  has_many :board_users, dependent: :destroy
  has_many :users, through: :board_users

  validates :name, presence: true
  validates :color, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmation_workspace, only: [:show, :new, :create]
  before_action :confirmation_board, only: [:destroy]

  def index
    @boards = current_user.boards.includes(:workspace)
  end

  def show
    @board = Board.includes(:task_lists, :tasks, :users).find(params[:id])
    @task_lists = @board.task_lists
    @users = @board.users
  end

  def edit
    @board = Board.includes(:users).find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save and @board.users << current_user
      redirect_to workspace_url(params[:workspace_id])
    else
      render :new
    end
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(update_params)
      redirect_to board_url(@board)
    else
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:id])
    if board.destroy
      redirect_to workspace_url(board.workspace_id)
    else
      render :new
    end
  end

  private
  def board_params
    params.require(:board).permit(:name, :color).merge(workspace_id: params[:workspace_id])
  end

  def update_params
    params.require(:board).permit(:name, :color)
  end

  def confirmation_board
    board = Board.find(params[:id])
    unless current_user.boards.include?(board)
      if current_user.workspaces.include?(board.workspace)
        redirect_to board, alert: "ボードに参加していないため変更を行えません。" and return
      else
        redirect_to root_url, alert: "そのボードは存在しません。" and return
      end
    end
  end

  def confirmation_workspace
    if params[:workspace_id].present?
      workspace = Workspace.find(params[:workspace_id])
    elsif params[:id].present?
      board = Board.find(params[:id])
      workspace = board.workspace
    else
      redirect_to root_url, alert: "エラーが発生しました。"
    end

    unless current_user.workspaces.include?(workspace)
      redirect_to root_url, alert: "そのワークスペースは存在しません。"
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.erb
<div class="container mx-auto">
  <div class="mt-8">
    <div class="relative">
      <h2 class="text-center text-2xl font-bold">ボード編集</h2>
      <%= link_to "削除", board_path(@board), method: :delete, class: "block absolute right-0 px-3 py-1 rounded bg-red-600 text-white", data: { confirm: "本当に削除しますか？" } %>
    </div>
    <%= form_with model: @board, url: board_path(@board) do |f|  %>
      <%= f.label :name, class: "block mt-6 font-bold" %>
      <%= f.text_field :name, class: "block w-full rounded-lg shadow border-gray-400", autofocus: true %>
        <p class="field_with_errors text-right"><%= @board.errors.full_messages_for(:name).first %></p>

      <%= f.label :color, class: "block mt-6 font-bold" %>
      <%= f.color_field :color %>
      <p class="field_with_errors text-right"><%= @board.errors.full_messages_for(:color).first %></p>

      <%= f.submit "変更", class: "block w-full mt-2 py-2 rounded shadow border bg-green-600 text-white" %>
    <% end %>
    <%= link_to "キャンセル", board_path(@board), class: "block py-2 px-auto text-center underline" %>
  </div>

  <div>
    <% @board.users.each do |user| %>
      <%= user.unique_id %>
    <% end %>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container mx-auto">
  <div class="my-8">
    <h2 class="text-3xl text-center font-bold">所属ボード一覧</h2>
  </div>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
    <% @boards.each do |board| %>
      <div class="col-span-1 panel-3d h-24 rounded-md border border-gray-600 shadow-md shadow-gray-400 hover:shadow-gray-600" style="background-color: <%= board.color%>;">
        <%= link_to board, class: "group block h-full p-2" do %>
          <p class="font-bold text-white text-lg group-hover:underline"><%= board.name %></p>
          <p class="text-sm"><%= board.workspace.name %></p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container mx-auto items-center">
  <h2 class="my-8 text-center text-3xl font-bold">ボード追加</h2>
  <%= form_with model: @board, url: workspace_boards_path, class: "space-y-4" do |f| %>
    <div>
      <%= f.label :name, class: "block font-bold" %>
      <%= f.text_field :name, class: "block w-full mt-1 rounded-lg border-gray-400", autofocus: true %>
      <p class="field_with_errors text-right"><%= @board.errors.full_messages_for(:name).first %></p>
    </div>

    <div>
      <%= f.label :color, class: "block font-bold" %>
      <%= f.color_field :color %>
      <p class="field_with_errors text-right"><%= @board.errors.full_messages_for(:color).first %></p>
    </div>

    <%= f.submit "作成", class: "w-full mt-4 py-2 bg-blue-500 border text-white" %>
  <% end %>
</div>

app/views/boards/show.html.erb
<div class="flex flex-col min-h-[calc(100vh-5rem)]">
  <div class="flex h-12 items-center space-x-4">
    <h2 class="ml-4 px-3 border-r-2 border-gray-400 font-bold"><%= @board.name %></h2>
    <div class="flex flex-shrink-0 items-center space-x-4">
      <% if @users.present? %>
        <ul class="flex overflow-x-auto items-center w-44 space-x-2">
          <% @users.each do |user| %>
            <li><%= user.unique_id %></li>
          <% end %>
        </ul>
      <% end %>
      <% unless @users.include?(current_user) %>
        <p><%= link_to "参加", board_board_users_path(@board), method: :post %></p>
      <% end %>
    </div>
    <%= link_to "ボード編集", edit_board_path, class: "underline" %>
  </div>

  <ul class="flex-grow flex overflow-x-scroll items-start mt-2 px-8 space-x-4">
    <% if @task_lists.present? %>
      <% @task_lists.each do |task_list| %>
        <li class="flex-none w-64 p-3 rounded-lg border border-black bg-gray-200 shadow-md shadow-gray-400">
          <h3 class="text-lg font-bold"><%= task_list.name %></h3>
          <% if task_list.tasks.present? %>
            <ul class="mt-2 space-y-2">
              <% task_list.tasks.each do |task| %>
                <li class="rounded bg-white border border-gray-400 shadow shadow-gray-400 hover:shadow-gray-600"><%= link_to task.title, task, class: "block w-full h-full p-2" %></li>
              <% end %>
            </ul>
          <% end %>
          <%= link_to "タスク追加", new_task_list_task_path(task_list), class: "block mt-1 underline" %>
          <%= link_to "リストを削除", task_list_path(task_list), method: :delete, class: "underline", data: {confirm: "本当にリストを削除しますか？"} %>
        </li>
      <% end %>
    <% end %>

    <div class="p-3 rounded-t-lg bg-gray-200 border border-black shadow-md shadow-gray-400">
      <%= link_to "リストを追加", new_board_task_list_path(@board), class: "flex-none block w-64 underline font-bold" %>
    </div>
  </ul>
</div>